name: Update readme

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 10,22 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Generate readme
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
        run: node ./src/index.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Beep boop beep boop: update 😊"
          commit_user_name: nhendra
          commit_user_email: 99159109+NHendra@users.noreply.github.com
          commit_author: nhendra <99159109+NHendra@users.noreply.github.com>
          file_pattern: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.READ_TOKEN }}